// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package productspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsClient interface {
	GetShoes(ctx context.Context, in *ShoesRequest, opts ...grpc.CallOption) (*ShoesResponse, error)
	GetShoe(ctx context.Context, in *ShoeRequest, opts ...grpc.CallOption) (*ShoeResponse, error)
}

type productsClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsClient(cc grpc.ClientConnInterface) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) GetShoes(ctx context.Context, in *ShoesRequest, opts ...grpc.CallOption) (*ShoesResponse, error) {
	out := new(ShoesResponse)
	err := c.cc.Invoke(ctx, "/products.Products/GetShoes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) GetShoe(ctx context.Context, in *ShoeRequest, opts ...grpc.CallOption) (*ShoeResponse, error) {
	out := new(ShoeResponse)
	err := c.cc.Invoke(ctx, "/products.Products/GetShoe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
// All implementations must embed UnimplementedProductsServer
// for forward compatibility
type ProductsServer interface {
	GetShoes(context.Context, *ShoesRequest) (*ShoesResponse, error)
	GetShoe(context.Context, *ShoeRequest) (*ShoeResponse, error)
	mustEmbedUnimplementedProductsServer()
}

// UnimplementedProductsServer must be embedded to have forward compatible implementations.
type UnimplementedProductsServer struct {
}

func (UnimplementedProductsServer) GetShoes(context.Context, *ShoesRequest) (*ShoesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShoes not implemented")
}
func (UnimplementedProductsServer) GetShoe(context.Context, *ShoeRequest) (*ShoeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShoe not implemented")
}
func (UnimplementedProductsServer) mustEmbedUnimplementedProductsServer() {}

// UnsafeProductsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServer will
// result in compilation errors.
type UnsafeProductsServer interface {
	mustEmbedUnimplementedProductsServer()
}

func RegisterProductsServer(s grpc.ServiceRegistrar, srv ProductsServer) {
	s.RegisterService(&Products_ServiceDesc, srv)
}

func _Products_GetShoes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShoesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetShoes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.Products/GetShoes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetShoes(ctx, req.(*ShoesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_GetShoe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShoeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).GetShoe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.Products/GetShoe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).GetShoe(ctx, req.(*ShoeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Products_ServiceDesc is the grpc.ServiceDesc for Products service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Products_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "products.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShoes",
			Handler:    _Products_GetShoes_Handler,
		},
		{
			MethodName: "GetShoe",
			Handler:    _Products_GetShoe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microservices/products/products.proto",
}
