// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: microservices/products/products.proto

package productspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShoesRequest) Reset() {
	*x = ShoesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_products_products_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShoesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoesRequest) ProtoMessage() {}

func (x *ShoesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_products_products_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoesRequest.ProtoReflect.Descriptor instead.
func (*ShoesRequest) Descriptor() ([]byte, []int) {
	return file_microservices_products_products_proto_rawDescGZIP(), []int{0}
}

type ShoesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shoes []*ShoeResponse `protobuf:"bytes,1,rep,name=shoes,proto3" json:"shoes,omitempty"`
}

func (x *ShoesResponse) Reset() {
	*x = ShoesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_products_products_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShoesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoesResponse) ProtoMessage() {}

func (x *ShoesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_products_products_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoesResponse.ProtoReflect.Descriptor instead.
func (*ShoesResponse) Descriptor() ([]byte, []int) {
	return file_microservices_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *ShoesResponse) GetShoes() []*ShoeResponse {
	if x != nil {
		return x.Shoes
	}
	return nil
}

type ShoeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ShoeRequest) Reset() {
	*x = ShoeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_products_products_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShoeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoeRequest) ProtoMessage() {}

func (x *ShoeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_products_products_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoeRequest.ProtoReflect.Descriptor instead.
func (*ShoeRequest) Descriptor() ([]byte, []int) {
	return file_microservices_products_products_proto_rawDescGZIP(), []int{2}
}

func (x *ShoeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ShoeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ShoeResponse) Reset() {
	*x = ShoeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_products_products_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShoeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoeResponse) ProtoMessage() {}

func (x *ShoeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_products_products_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoeResponse.ProtoReflect.Descriptor instead.
func (*ShoeResponse) Descriptor() ([]byte, []int) {
	return file_microservices_products_products_proto_rawDescGZIP(), []int{3}
}

func (x *ShoeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShoeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShoeResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_microservices_products_products_proto protoreflect.FileDescriptor

var file_microservices_products_products_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x53, 0x68, 0x6f,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x65, 0x73,
	0x22, 0x1d, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x48, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x81, 0x01, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x53, 0x68,
	0x6f, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x65, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x2e, 0x53, 0x68, 0x6f, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a,
	0x18, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_microservices_products_products_proto_rawDescOnce sync.Once
	file_microservices_products_products_proto_rawDescData = file_microservices_products_products_proto_rawDesc
)

func file_microservices_products_products_proto_rawDescGZIP() []byte {
	file_microservices_products_products_proto_rawDescOnce.Do(func() {
		file_microservices_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(file_microservices_products_products_proto_rawDescData)
	})
	return file_microservices_products_products_proto_rawDescData
}

var file_microservices_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_microservices_products_products_proto_goTypes = []interface{}{
	(*ShoesRequest)(nil),  // 0: products.ShoesRequest
	(*ShoesResponse)(nil), // 1: products.ShoesResponse
	(*ShoeRequest)(nil),   // 2: products.ShoeRequest
	(*ShoeResponse)(nil),  // 3: products.ShoeResponse
}
var file_microservices_products_products_proto_depIdxs = []int32{
	3, // 0: products.ShoesResponse.shoes:type_name -> products.ShoeResponse
	0, // 1: products.Products.GetShoes:input_type -> products.ShoesRequest
	2, // 2: products.Products.GetShoe:input_type -> products.ShoeRequest
	1, // 3: products.Products.GetShoes:output_type -> products.ShoesResponse
	3, // 4: products.Products.GetShoe:output_type -> products.ShoeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_microservices_products_products_proto_init() }
func file_microservices_products_products_proto_init() {
	if File_microservices_products_products_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microservices_products_products_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShoesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_products_products_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShoesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_products_products_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShoeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_products_products_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShoeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microservices_products_products_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microservices_products_products_proto_goTypes,
		DependencyIndexes: file_microservices_products_products_proto_depIdxs,
		MessageInfos:      file_microservices_products_products_proto_msgTypes,
	}.Build()
	File_microservices_products_products_proto = out.File
	file_microservices_products_products_proto_rawDesc = nil
	file_microservices_products_products_proto_goTypes = nil
	file_microservices_products_products_proto_depIdxs = nil
}
