// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package microservicespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroservicesClient is the client API for Microservices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroservicesClient interface {
	CreateCharge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
	SendConfirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error)
}

type microservicesClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroservicesClient(cc grpc.ClientConnInterface) MicroservicesClient {
	return &microservicesClient{cc}
}

func (c *microservicesClient) CreateCharge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, "/microservices.Microservices/CreateCharge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microservicesClient) SendConfirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/microservices.Microservices/SendConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroservicesServer is the server API for Microservices service.
// All implementations must embed UnimplementedMicroservicesServer
// for forward compatibility
type MicroservicesServer interface {
	CreateCharge(context.Context, *ChargeRequest) (*ChargeResponse, error)
	SendConfirmation(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error)
	mustEmbedUnimplementedMicroservicesServer()
}

// UnimplementedMicroservicesServer must be embedded to have forward compatible implementations.
type UnimplementedMicroservicesServer struct {
}

func (UnimplementedMicroservicesServer) CreateCharge(context.Context, *ChargeRequest) (*ChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCharge not implemented")
}
func (UnimplementedMicroservicesServer) SendConfirmation(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConfirmation not implemented")
}
func (UnimplementedMicroservicesServer) mustEmbedUnimplementedMicroservicesServer() {}

// UnsafeMicroservicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroservicesServer will
// result in compilation errors.
type UnsafeMicroservicesServer interface {
	mustEmbedUnimplementedMicroservicesServer()
}

func RegisterMicroservicesServer(s grpc.ServiceRegistrar, srv MicroservicesServer) {
	s.RegisterService(&Microservices_ServiceDesc, srv)
}

func _Microservices_CreateCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroservicesServer).CreateCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.Microservices/CreateCharge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroservicesServer).CreateCharge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Microservices_SendConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroservicesServer).SendConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservices.Microservices/SendConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroservicesServer).SendConfirmation(ctx, req.(*ConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Microservices_ServiceDesc is the grpc.ServiceDesc for Microservices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Microservices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microservices.Microservices",
	HandlerType: (*MicroservicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCharge",
			Handler:    _Microservices_CreateCharge_Handler,
		},
		{
			MethodName: "SendConfirmation",
			Handler:    _Microservices_SendConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microservices/microservices.proto",
}
